version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - .:/app
    container_name: backend
    expose:
      - 5000